// Brute Force Code & Optimal Code
class Solution {
public:
    // store all possible letter combinations generated by the backtracking process.
    vector<string> result;
    void solve(int idx, string& digits, string& temp,
               unordered_map<char, string>& mp) {
        // base case: if  have processed every digit the current string is a complete letter combination.
        if (idx >= digits.length()) {
            // store the current combination.
            result.push_back(temp);
            return;
        }
        // get the current digit.
        char ch = digits[idx];
        // get all letters mapped to the current digit.
        string letters = mp[ch];
        // try every possible letter for the current digit.
        for (int i = 0; i < letters.length(); i++) {
            // choose add the current letter to the combination.
            temp.push_back(letters[i]);
            // explore move to the next digit.
            solve(idx + 1, digits, temp, mp);
            // backtrack remove the last chosen letter.
            temp.pop_back();
        }
    }
    vector<string> letterCombinations(string digits) {
        // if the input is empty there are no possible combinations.
        if (digits.length() == 0) {
            return {};
        }
        // phone keypad mapping each digit maps to a group of letters.
        unordered_map<char, string> mp = {{'2', "abc"},{'3', "def"},{'4', "ghi"},{'5', "jkl"},{'6', "mno"},{'7', "pqrs"},{'8', "tuv"},{'9', "wxyz"}
        };
        // store the current combination while building it recursively.
        string temp = "";
        // start the backtracking process from the first digit.
        solve(0, digits, temp, mp);
        // return all generated combinations.
        return result;
    }
};

// Time Complexity : O(N)
// Space Complexity : O(N)