# Brute Force Code & Optimal Code
class Solution:
    def __init__(self):
        # store all possible letter combinations generated by the backtracking process.
        self.result = []
    def solve(self, idx, digits, temp, mp):
        # base case: if have processed every digit the current string is a complete letter combination.
        if idx >= len(digits):
            # store the current combination.
            self.result.append(temp)
            return
        # get the current digit
        ch = digits[idx]
        # get all letters mapped to the current digit.
        letters = mp[ch]
        # try every possible letter for the current digit, try each letter one by one.
        for i in range(len(letters)):
            # choose add the current letter to the combination being constructed.
            temp += letters[i]
            # explore move to the next digit and continue building the combination.
            self.solve(idx + 1, digits, temp, mp)
            # backtrack remove the last chosen letter this restores temp to its previous state so that we can try the next letter.
            temp = temp[:-1]
    def letterCombinations(self, digits: str) -> list[str]:
        # if the input is empty there are no possible combinations.
        if len(digits) == 0:
            return []
        # phone keypad mapping each digit maps to a group of letters.
        mp = {'2': "abc", '3': "def", '4': "ghi", '5': "jkl", '6': "mno",'7': "pqrs", '8': "tuv", '9': "wxyz"}
        # store the current combination while building it recursively.
        temp = ""
        # start the backtracking process from the first digit.
        self.solve(0, digits, temp, mp)
        # return all generated combinations.
        return self.result

# Time Complexity : O(N)
# Space Complexity : O(N)